### ISSUE TITLE
Find dataset

### ISSUE THREAD

**Issue by SebMon** [SebMon/DataVis#1]
Link suggestions for datasets in comments. We probably want a dataset with a good amount of different relevant variables we can work with, such as date, length, color, or whatever.

**Comment by ValeleDK** [comment]
https://www.kaggle.com/datasets/trolukovich/steam-games-complete-dataset

This dataset has a lot of different variables over steam games. Like overall reviews (like 80% positive), recent review, tags, developer and much more.

**Comment by ValeleDK** [comment]
https://www.kaggle.com/datasets/nabilajahan/the-impact-of-electronic-gadget-uses

Also has a lot of variables and sounds interesting.

**Comment by magnuskjaer** [comment]
https://www.kaggle.com/datasets/spscientist/students-performance-in-exams

**Comment by SebMon** [comment]
https://www.kaggle.com/datasets/jgiigii/uscrimesdataset

**Comment by SebMon** [comment]
https://www.kaggle.com/datasets/kevinmorgado/us-energy-generation-2001-2022

**Comment by SebMon** [comment]
https://catalog.data.gov/dataset/crime

**Comment by SebMon** [comment]
Information about each column of the dataset can be found [here](https://data.montgomerycountymd.gov/Public-Safety/Crime/icn6-v9z3)
